name: Build APK in GitHub Actions

on:
  push:
    branches:
      - build

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Update package list and install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build libgtk-3-dev nano

      # Step 3: Clone Flutter SDK
      - name: Clone Flutter SDK
        run: |
          git clone --quiet https://github.com/flutter/flutter.git -b stable
          echo "Flutter SDK cloned"

      # Step 4: Install Android SDK Command Line Tools
      - name: Install Android SDK Command Line Tools
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9862592_latest.zip
          mkdir -p Android/Sdk
          unzip -q commandlinetools-linux-9862592_latest.zip -d Android/Sdk
          export ANDROID_HOME=$(pwd)/Android/Sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV  # Export the environment variable

      # Step 5: Set up Android SDK environment variables
      - name: Set up environment variables for Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          export PATH="$PATH:$ANDROID_HOME:$ANDROID_HOME/emulator:$ANDROID_HOME/cmdline-tools:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools"
          export PATH="$PATH:$(pwd)/flutter/bin"
          echo "PATH=$PATH" >> $GITHUB_ENV  # Export PATH to environment variables

      # Step 6: Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --sdk_root=${ANDROID_HOME} "tools"
          yes | sdkmanager --update --sdk_root=${ANDROID_HOME}
          sdkmanager --list --sdk_root=${ANDROID_HOME}
          yes | sdkmanager "platform-tools" "platforms;android-31" "tools" "cmdline-tools;latest" "build-tools;31.0.0" --sdk_root=${ANDROID_HOME}
          yes | sdkmanager --licenses --sdk_root=${ANDROID_HOME}

      # Step 7: Install Gradle
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.0-bin.zip
          unzip -q gradle-7.0-bin.zip
          sudo mv gradle-7.0 /opt/gradle
          echo "export PATH=$PATH:/opt/gradle/bin" >> ~/.bashrc
          source ~/.bashrc

      # Step 8: Navigate to the Flutter project directory and build the APK
      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we're in the root of the repository (where pubspec.yaml is)
          flutter doctor
          flutter build apk --release

      # Step 9: Upload the APK as an artifact (optional)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
